---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
      command: echo
      arguments: 
      - "Deploy of hello-app on ${ENV_NAME}"
  test-tasks: &test-tasks
    - exec:
      command: echo
      arguments: 
      - "Test of hello-app on ${ENV_NAME}"
pipelines:
  hello-app:
    group: java-spring-apps
    materials:
      mygit:
        git: https://github.com/vjerihova/hello-gradle-ci.git
        branch: main
    stages:
      - build-app:
          jobs:
            build-app:
              tasks:
              - exec:
                  command: echo
                  arguments: 
                  - "Building hello app"
      - deploy-dev:
          environment_variables:
            ENV_NAME: dev
          jobs:
            deploy-dev:
              tasks: *deploy-tasks
      - test-dev:
          environment_variables:
            ENV_NAME: dev
          jobs:
            test-dev:
              tasks: *test-tasks
      - deploy-prd:
          environment_variables:
            ENV_NAME: prd
          jobs:
            deploy-prd:
              tasks: *deploy-tasks
      - test-prd:
          environment_variables:
            ENV_NAME: prd
          jobs:
            test-prd:
              tasks: *test-tasks